import { PersonalInfo, WorkExperience, Project, Education, SkillCategory } from "@/types/resume"

export const personalInfo: PersonalInfo = {
  name: "IBRAHIM TAJUDEEN",
  title: "Software Engineer",
  tagline: "Full-Stack Developer • System Architect • Compiler Enthusiast",
  location: "Nigeria / Remote",
  portfolio: "https://www.nexocode.vercel.app",
  resumeWebsite: "https://www.nexocode-cv.vercel.app",
  github: "https://github.com/ibrahimtajudeen",
  linkedin: "https://www.linkedin.com/in/ibrahim-tajudeen-7328312a5",
  email: "donslice6@gmail.com",
  phone: "+234 813 216 6576",
  summary: `Software Engineer experienced in building scalable backend systems, fintech infrastructure, AI-powered platforms, and cross-platform applications across web, desktop, and mobile environments. Skilled in designing secure APIs, payment systems, real-time architectures, authentication systems, and modern frontend experiences using technologies such as C#, .NET, NestJS, React.js, and PostgreSQL.`,
}

export const professionalSummary = personalInfo.summary!

export const skillCategories: SkillCategory[] = [
  {
    id: "cat-1",
    name: "Languages",
    skills: ["JavaScript", "TypeScript", "C/C++", "C#", "Java", "Python", "SQL"],
    icon: "Code2",
  },
  {
    id: "cat-2",
    name: "Frontend & Cross Platform",
    skills: ["React.js", "Next.js", "Blazor", "React Native", "Flutter", "Xamarin.Forms", ".NET MAUI", "WPF", "UWP", "WinForms", "Tailwind CSS", "Bootstrap", "EJS", "PUG", "Handlebars"],
    icon: "Layout",
  },
  {
    id: "cat-3",
    name: "Backend & APIs",
    skills: ["Node.js", "Express.js", "NestJS", "ASP.NET", "Spring Boot", "FastAPI", "Django", "Flask"],
    icon: "Server",
  },
  {
    id: "cat-4",
    name: "Databases",
    skills: ["PostgreSQL", "MySQL", "SQL Server", "Redis", "MongoDB", "Supabase", "Firebase"],
    icon: "Database",
  },
  {
    id: "cat-5",
    name: "Authentication & Security",
    skills: ["JWT", "OAuth2", "RBAC", "API Security", "Secure Payment Flows", "Encryption", "Row-Level Security"],
    icon: "Shield",
  },
  {
    id: "cat-6",
    name: "DevOps & Tools",
    skills: ["Git", "GitHub Actions", "GitLab", "Bitbucket", "Azure DevOps", "Jenkins", "Docker", "CI/CD"],
    icon: "GitBranch",
  },
  {
    id: "cat-7",
    name: "AI & Integrations",
    skills: ["OpenAI APIs", "NLP", "TensorFlow", "Payment APIs", "WebSockets"],
    icon: "Brain",
  },
]

export const workExperience: WorkExperience[] = [
  {
    id: "exp-1",
    company: "STONETECH SQUARE",
    role: "Software Engineer",
    period: "2024 – 2025",
    responsibilities: [
      "Developed fintech and peer-to-peer transaction platforms using NestJS, React.js, Supabase, and PostgreSQL.",
      "Built wallet infrastructure supporting virtual accounts, fund transfers, transaction auditing, and secure financial operations.",
      "Integrated Bybit P2P APIs to facilitate secure merchant-to-user transaction workflows.",
      "Implemented Row-Level Security (RLS), encryption layers, and identity validation systems to strengthen platform security.",
      "Contributed to backend architecture, database design, API development, and frontend integration across production systems.",
      "Collaborated with engineering teams to optimize application performance, scalability, and maintainability.",
    ],
    keyProject: "SkuidPay — P2P Fintech Platform",
    technologies: ["NestJS", "React.js", "Supabase", "PostgreSQL", "Bybit APIs"],
    achievements: [
      "Built wallet systems with virtual account management, transaction history, and fund transfer capabilities.",
      "Designed secure transaction workflows with merchant verification and identity protection mechanisms.",
      "Implemented secure authentication, encryption, and fraud prevention systems.",
    ],
  },
  {
    id: "exp-2",
    company: "SCORCHETECH",
    role: "Software Engineer",
    period: "Jan 2023 – Jan 2024",
    responsibilities: [
      "Developed scalable web and mobile applications across fintech and enterprise product ecosystems.",
      "Built secure backend services and responsive frontend systems using Node.js, React.js, and PostgreSQL.",
      "Integrated payment processing APIs and implemented transaction-safe financial workflows.",
      "Improved system performance, API reliability, and frontend responsiveness through debugging and optimization.",
      "Participated in architecture planning, API design, and product development processes.",
    ],
    keyProject: "ScorchePay — Fintech Platform",
    technologies: ["Node.js", "React.js", "PostgreSQL", "Payment APIs"],
    achievements: [
      "Built wallet systems supporting virtual accounts, transfers, audit trails, and transaction history.",
      "Implemented idempotent transaction handling and scalable fintech architecture.",
      "Developed secure RBAC authentication systems and fraud-prevention mechanisms.",
      "Integrated payment processing APIs for secure financial operations.",
    ],
  },
  {
    id: "exp-3",
    company: "NEXOTECHNOLOGY LIMITED",
    role: "Software Engineer",
    period: "2023 – Present",
    responsibilities: [
      "Led development of enterprise software systems, AI-powered platforms, fintech applications, and internal developer tools.",
      "Designed scalable backend APIs, database architectures, authentication systems, and real-time communication workflows.",
      "Built cross-platform applications across web, desktop, and mobile environments using modern engineering frameworks.",
      "Worked on AI integrations, secure data systems, automation workflows, and developer productivity tools.",
      "Contributed to technical architecture decisions, deployment workflows, and engineering system design.",
    ],
    keyProject: "Enterprise Solutions & Developer Tools",
    technologies: ["C#", ".NET", "NestJS", "React.js", "PostgreSQL", "Azure DevOps"],
    achievements: [
      "Architected scalable enterprise systems with microservices patterns.",
      "Built developer tooling platforms improving team productivity.",
      "Implemented AI-powered features across multiple product lines.",
    ],
  },
]

export const projects: Project[] = [
  {
    id: "proj-1",
    name: "KalmScript",
    tech: ["C#", "C/C++", "MSIL"],
    highlights: [
      "Custom compiler architecture",
      "Lexer/parser/AST system",
      "Multi-language interoperability",
      "Unified MSIL execution",
      "Sandboxed runtime",
      "DLL dependency management",
    ],
    category: "Systems Programming",
    project_type: "public",
    github_url: "https://github.com/ibrahimtajudeen/kalmscript",
    demo_url: null,
    featured: true,
  },
  {
    id: "proj-2",
    name: "DevGroupHub",
    tech: ["Node.js", "GitHub APIs", "Automation Systems"],
    highlights: [
      "GitHub repository watchdog systems",
      "WhatsApp automation bots",
      "Team collaboration systems",
    ],
    category: "Developer Tools",
    project_type: "public",
    github_url: "https://github.com/ibrahimtajudeen/devgrouphub",
    demo_url: "https://devgrouphub.vercel.app",
    featured: true,
  },
  {
    id: "proj-3",
    name: "SaleTrack",
    tech: ["ASP.NET", "SQL Server", "React.js"],
    highlights: [
      "Inventory management",
      "Sales auditing",
      "Analytics dashboards",
      "Fraud prevention systems",
    ],
    category: "Enterprise",
    project_type: "customer",
    github_url: null,
    demo_url: "https://saletrack-demo.vercel.app",
    featured: true,
  },
  {
    id: "proj-4",
    name: "FinSight",
    tech: ["React.js", "Supabase", "OpenAI APIs"],
    highlights: [
      "AI-powered recommendations",
      "Banking API integrations",
      "Financial tracking systems",
    ],
    category: "Fintech",
    project_type: "public",
    github_url: "https://github.com/ibrahimtajudeen/finsight",
    demo_url: "https://finsight-ai.vercel.app",
    featured: true,
  },
  {
    id: "proj-5",
    name: "QuickRun",
    tech: ["Flutter", "Node.js", "Payment APIs"],
    highlights: [
      "Utility payment APIs",
      "Referral systems",
      "Wallet interactions",
    ],
    category: "Fintech",
    project_type: "customer",
    github_url: null,
    demo_url: "https://quickrun.app",
    featured: false,
  },
  {
    id: "proj-6",
    name: "Hospital Management System",
    tech: ["ASP.NET", "SQL Server", "React.js"],
    highlights: [
      "Multi-branch architecture",
      "Role-based authorization",
      "Digital hospital operations",
    ],
    category: "Healthcare",
    project_type: "customer",
    github_url: null,
    demo_url: null,
    featured: false,
  },
  {
    id: "proj-7",
    name: "School Management System",
    tech: ["ASP.NET", "SQL Server", "React.js"],
    highlights: [
      "Dynamic dashboards",
      "Multi-role systems",
      "Multi-branch architecture",
    ],
    category: "Education",
    project_type: "customer",
    github_url: null,
    demo_url: null,
    featured: false,
  },
  {
    id: "proj-8",
    name: "ISQL",
    tech: ["C#", ".NET"],
    highlights: [
      "Custom SQL-like library",
      "Hashing & encryption",
      "Custom data structures",
    ],
    category: "Systems Programming",
    project_type: "public",
    github_url: "https://github.com/ibrahimtajudeen/isql",
    demo_url: null,
    featured: false,
  },
  {
    id: "proj-9",
    name: "Auth-Folio",
    tech: ["ASP.NET", "JWT", "REST APIs"],
    highlights: [
      "Reusable authentication APIs",
      "JWT identity management",
      "Secure integrations",
    ],
    category: "Security",
    project_type: "public",
    github_url: "https://github.com/ibrahimtajudeen/auth-folio",
    demo_url: null,
    featured: false,
  },
  {
    id: "proj-10",
    name: "FuturePlanners",
    tech: ["React.js", "Node.js", "PostgreSQL"],
    highlights: [
      "Real-time notifications",
      "Scalable backend APIs",
      "Property workflows",
    ],
    category: "Real Estate",
    project_type: "private",
    github_url: null,
    demo_url: "https://futureplanners.com",
    featured: false,
  },
  {
    id: "proj-11",
    name: "Standard Safe Construction",
    tech: ["Express.js", "MongoDB", "Cloudinary", "AI APIs"],
    highlights: [
      "AI-powered recommendations",
      "Payment gateway systems",
      "Media management systems",
    ],
    category: "Construction",
    project_type: "customer",
    github_url: null,
    demo_url: "https://standardsafe.com",
    featured: false,
  },
  {
    id: "proj-12",
    name: "AI-Based Phishing Detection",
    tech: ["Python", "TensorFlow", "REST APIs", "PowerShell"],
    highlights: [
      "TF-IDF vectorization",
      "Machine learning classification",
      "REST communication systems",
      "PowerShell automation",
    ],
    category: "AI/ML",
    project_type: "public",
    github_url: "https://github.com/ibrahimtajudeen/ai-phishing-detection",
    demo_url: null,
    featured: false,
  },
]

export const education: Education[] = [
  { id: "edu-1", degree: "Diploma in Software Engineering", institution: "Kaduna ICT Hub" },
  { id: "edu-2", degree: "Diploma in ICT", institution: "Dialogue ICT Schools" },
  { id: "edu-3", degree: "Diploma in Computer Literacy & Programming Fundamentals", institution: "Notion Computer Technology" },
  { id: "edu-4", degree: "WAEC", institution: "WAEC Board", year: "2020" },
  { id: "edu-5", degree: "NECO", institution: "NECO Board", year: "2020" },
]

export const leadershipAndStrengths = [
  "Led architecture and development for fintech systems, authentication platforms, AI-powered solutions, and developer tooling projects.",
  "Strong expertise in backend API development, scalable system architecture, database optimization, and secure application engineering.",
  "Experienced in designing financial systems including wallet infrastructure, transaction workflows, reconciliation logic, and secure payment integrations.",
  "Skilled in cross-platform application development across web, desktop, and mobile ecosystems.",
  "Comfortable owning projects end-to-end from planning and architecture through deployment and production optimization.",
  "Strong problem-solving mindset with experience building production-oriented systems under real-world engineering constraints.",
  "Focused on clean architecture, maintainable codebases, scalable infrastructure, and modern software engineering best practices.",
]
